### ISSUE TITLE
Publishing to GitHub Pages still isn't working

### ISSUE THREAD

**Issue by alyssaterrell** [SCBI-ForestGEO/SCBI-Plot-Book#11]
Publishing to GitHub Pages still isn't working, even with the improved code (thank you, @maurolepore!). After reading more about [GitHub Pages](https://pages.github.com/), I thought maybe adding an index.html file and moving the location of the README file would do the trick but that hasn't worked either. Open to any new suggestions!

Who knew coding would be so hard! LOL.🙃😢

**Comment by teixeirak** [comment]
Backing up a bit, I wouldn't make worrying about the website a top priority right now. If you can get it done without too much struggle, great. If not, set that aside for a bit.  @maurolepore's visit in January might be a good time to work through it.

**Comment by maurolepore** [comment]
@alyssaterrell, I think the problem is that you are missing a first-level heading in index.Rmd. See [index.Rmd in my fork](https://github.com/maurolepore/SCBI-Plot-Book/blob/18f6dfc37edd5fdf1648ba46138ce73de29a8435/index.Rmd#L18).

It's been a long while since I worked on a bookdown. I don't know why you are forced to having such a heading not I know how to get around that. I bet the answer is somewhere in the bookdown book. Let me if you find out. @teixeirak is right and I can help you in person. but this is a great way to practice a generally useful workflow. :)

**Comment by maurolepore** [comment]
RE: 
> moving the location of the README file would do the trick but that hasn't worked either.

I think it's save to move README.Rmd back to the root. That is because GitHub pages should look into /docs to build the website -- not on the root.

**Comment by gonzalezeb** [comment]
I think I got it to work (maybe??). It seems that there was a step missing: _Enabling GitHub Pages to publish your site from master_ [check here](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages)

**Comment by mcgregorian1** [comment]
This looks like what we were going for!
