### ISSUE TITLE
explore species range map data

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBI-Plot-Book#2]
[BIEN](http://biendata.org/): -> can download current range maps as polygons .shp

[GBIF](https://www.gbif.org/): -> maps of species occurrences, can download individual points as zip and create range if needed

[Map of life](https://mol.org/): -> range maps are Little 1971

[USFS Tree Atlas](https://www.nrs.fs.fed.us/atlas/tree/): -> most thorough
- Little 1971 range maps
- current distribution range
- future range distribution
- compare ranges with different Hadley climate scenarios

[ForeCASTS](https://www.geobabble.org/ForeCASTS/atlas.html): -> also good
- similar to USFS, different visualizations of maps
- plots current ranges against Hadley climate scenarios
- also plots with Parallel Climate Models (PCM)

**Comment by teixeirak** [comment]
So long as its free and you've determined that its the best option, I see now reason why not. I will send you the lab gmail account info.

**Comment by mcgregorian1** [comment]
@teixeirak @alyssaterrell 
Update

1. The easiest way to read in data is making simple range maps with a polygon in a shapefile (see [litumap](https://github.com/SCBI-ForestGEO/SCBI-Plot-Book/tree/master/maps_and_figures).

2. BIEN has an R package that automatically calls data so we wouldn't have to download 70+ shapefiles. However, Smithsonian firewall doesn't allow the SQL connection, which means it's useless for us. There is potentially a way to retrieve the data from an index site of BIEN, but the code needs to be troubleshooted. I will ask Valentine next week.

3. Not all species ranges are available on BIEN. I tried the next best thing (ForeCASTS) for polygon shapefiles, but after some hours of searching it turns out their map files (kmz/kml) are not in a format that can be used by us. This leaves two options.

      - Either we get as much data as we can from BIEN and then for the missing ranges I find some other way to create the polygons (e.g. manually from the points from GBIF)

      - Or, we find another site that has everything to be consistent.

**Comment by mcgregorian1** [comment]
Update:

All species maps have been made, the code works, and we don't need to bother with Google API key. Some species names differ slightly from what BIEN has but we've (with Erika) made final decisions for the names. I'm going to close this issue.

**Comment by teixeirak** [comment]
This is fantastic; thanks @mcgregorian1! Is it possible to shade in the range?

**Comment by mcgregorian1** [comment]
It should be. I'll have a go at that today
